### ISSUE TITLE
Can't Paste into Textmate API Key Dialog (Textmate 2)

### ISSUE THREAD

**Issue by timdmackey** [wakatime/textmate-wakatime#2]
Not a huge deal, but a pain in the butt nonetheless. I had to type out the API Key by hand, since for some reason the Textmate Dialog when you first install Wakatime wouldn't let me paste the API key.

Aside from that, the plugin seems to be working for me. Thanks a bunch!

**Comment by alanhamlett** [comment]
That's strange... I'll try to reproduce it. I'm using OS X.. which OS are you using?

**Comment by timdmackey** [comment]
I'm on OS X as well, v10.10.2

**Comment by timdmackey** [comment]
It's very possibly a bug with Textmate, I'm not sure though.

**Comment by alanhamlett** [comment]
Haha, forgot TM only runs on OS X :sweat_smile:

It happens to me too, but two-finger clicking then selecting `paste` works. Looks like a TextMate problem.

**Comment by alanhamlett** [comment]
I've added some info about this to the readme.
