### ISSUE TITLE
Doesn't ask for API Key

### ISSUE THREAD

**Issue by JanGorman** [wakatime/textmate-wakatime#3]
I installed the plugin but Textmate (2.0-beta.8) doesn't ask for the API key the next time I launch it. Textmate has variables in the settings menu, might be easier to use those?

**Comment by stanlemon** [comment]
I am also seeing this issue with the latest TextMate.

**Comment by alanhamlett** [comment]
First, can you check if you already have a `$HOME/.wakatime.cfg` file with your api key? The plugins share that config file, so it's possible that TM picked up your api key from there.

**Comment by stanlemon** [comment]
@alanhamlett Oh!!! That was totally my issue, my apologies! Might want to put that in the docs so guys like me don't bug ya. :smile:

**Comment by JanGorman** [comment]
Ok it's there. I second @stanlemon's comment that mentioning that in the README could be helpful ;)

**Comment by alanhamlett** [comment]
Hopefully this universal installer app will solve it:

https://github.com/wakatime/wakatime-desktop

**Comment by mknippen** [comment]
I also had this issue. I think the solution to this issue is a documentation fix.
