### ISSUE TITLE
The bundle “WakaTime” couldn’t be loaded because it is damaged or missing necessary resources.

### ISSUE THREAD

**Issue by elia** [wakatime/textmate-wakatime#4]
TextMate has stopped lading the plugin:

```
⤑ /Applications/TextMate.app/Contents/MacOS/TextMate                                                                                                     ~
2019-09-02 09:43:18.729 TextMate[5068:5683813] Failed to load ‘WakaTime’ (~/Library/Application Support/TextMate/PlugIns/WakaTime.tmplugin): The bundle “WakaTime” couldn’t be loaded because it is damaged or missing necessary resources.
```

I already tried running the command specified in https://github.com/wakatime/textmate-wakatime#troubleshooting

**Comment by gandarez** [comment]
Hi @elia,

Is this bug still happening?

**Comment by elia** [comment]
I think we can close this, I've been successfully using wake time for the last year so I guess it was fixed at some point 👍

**Comment by felipealfonsog** [comment]
I had to uninstall the Wakatime plugin for TextMate because despite my attempts to use it, the plugin proved to be non-functional and consistently caused TextMate to freeze completely.
